steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.1.9'
    script: terraform init
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.1.9'
    script: terraform plan
  - id: 'terraform apply'
    name: 'hashicorp/terraform:1.1.9'
    script: terraform apply --auto-approve
